### ISSUE TITLE
publish StringDistance module separately

### ISSUE THREAD

**Issue by vilterp** [rluiten/mailcheck#2]
…since it could be useful in a lot of other contexts! Super glad to see an implementation in pure Elm; thanks for your work :smile:

**Comment by rluiten** [comment]
I have published StringDistance as separate package now but it is showing up as not updated for 0.16. I have no idea how this can be as all I have used in last weeks is 0.16 :).

Mailcheck now uses the seperate package.
I still see a warning on elm packages that stringdistance has not been updated to 0.16 but I have no way to address taht problem, have asked a question on slack and irc at the moment.

**Comment by vilterp** [comment]
It shows up above the divider now. I have noticed behavior like this for
one of my libs too; not sure what's up. Thanks!
